### ISSUE TITLE
Mock data and human readable TODOs

### ISSUE THREAD

**Issue by JimmyLiu8351** [ness-lab/readcomb#5]
**TODO**

- [x] Arguement parsing and polishing for human version of readcomb
- [x] Modify logging statistics for bam filtering readcomb
- [ ] More testing between bam filtering and human readable readcomb
- [x] Change function names for human readable version for organization
- [x] Change sequences to mock_sequence functions
- [x] Use setattr() for the mock_create

**Comment by JimmyLiu8351** [comment]
- For arguements, changed -f, --filename to -b, --bam to be more explicit in the naming of parameters
- Changed fieldnames for the logging to match with the updated counter printing

**Comment by JimmyLiu8351** [comment]
- All function unique to phase_change_readable.py begin with human_...
- Importing functions from phase_change_filter.py into phase_change_readable.py
